[package]
name = "mapdiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = { version = "1.0.87"}
octocrab = "0.17.0"
flume = "0.10.14"
dmm-tools = { git = "https://github.com/SpaceManiac/SpacemanDMM/", features = ["png"] }
dreammaker = { git = "https://github.com/SpaceManiac/SpacemanDMM/" }
ahash = "0.8.0"
path-absolutize = "3.0.14"
jsonwebtoken = "8.1.1"
lazy_static = "1.4.0"
eyre = "0.6.8"
stable-eyre = "0.2"
rayon = "1.5.3"
derive_builder = "0.11.2"
once_cell = "1.15.0"
image = "0.24.4"
glob = "0.3.0"
diffbot_lib = { path = "../diffbot_lib" }
git2 = "0.15.0"
yaque = "0.6.4"
walkdir = "2.3.2"
delay_timer = "0.11.3"

[dependencies.rocket]
version = "0.5.0-rc.2"
