
private_key_path = "/path/to/private/key"
file_hosting_url = "http://my_domain.com/files"
app_id = 42069
blacklist = [
	1337,
]
blacklist_contact = "Good luck!"
gc_schedule = "0 0 4 * * *"
logging = "info"
