[workspace]
members = [
    "crates/diffbot_lib",
    "crates/icondiffbot2",
    "crates/icondiffbot_test_generator",
    "crates/mapdiffbot2",
]

[profile.dev]
opt-level = 2

[profile.release]
lto = true
debug = true
