[package]
name = "icondiffbot2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
octocrab = { git = "https://github.com/XAMPPRocky/octocrab" }
# TODO: fix this when maniac merges my damn pr
dmm-tools = { git = "https://github.com/tigercat2000/SpacemanDMM/", branch = "memory_rw", features = ["png"] }
dreammaker = { git = "https://github.com/tigercat2000/SpacemanDMM/", branch = "memory_rw" }
once_cell = "1.10.0"
jsonwebtoken = "8"
lazy_static = "1.4.0"
reqwest = "0.11.10"
diffbot_lib = { path = "../diffbot_lib" }
anyhow = "1.0.57"
tokio = "1.18.1"
flume = "0.10.12"
ndarray = "0.15.3"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
