[package]
name = "icondiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
rmp-serde = "1.1.1"
octocrab = "0.17.0"
dmm-tools = { git = "https://github.com/SpaceManiac/SpacemanDMM/", features = ["png", "gif"] }
dreammaker = { git = "https://github.com/SpaceManiac/SpacemanDMM/" }
once_cell = "1.15.0"
jsonwebtoken = "8.1.1"
lazy_static = "1.4.0"
reqwest = "0.11.12"
diffbot_lib = { path = "../diffbot_lib" }
eyre = "0.6.8"
ndarray = "0.15.6"
rayon = "1.5.3"
toml = "0.5.9"
ahash = "0.8.0"
hashbrown = { version = "0.12.3", features = ["rayon"]}
yaque = "0.6.4"

actix-web = "4.2.1"
actix-files = "0.6.2"
async-fs = "1.6.0"
async-mutex = "1.4.0"

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
