[package]
name = "tinydmi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
tokio = "1.18.1"
ndarray = "0.15.3"
nom = "7.1.1"