[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
octocrab = "0.17.0"
eyre = "0.6.8"
derive_builder = "0.11.2"
chrono = "0.4.22"
reqwest = "0.11.12"
yaque = "0.6.4"
async-fs = "1.6.0"
futures-lite = "1.12.0"
log = "0.4.17"
simplelog = "0.12.0"
