[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
octocrab = { git = "https://github.com/XAMPPRocky/octocrab" }
anyhow = "1.0.57"
derive_builder = "0.11.2"
chrono = "0.4.19"
tokio = "1.18.1"
reqwest = "0.11.10"