[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = { version = "1.0.85"}
octocrab = { git = "https://github.com/tigercat2000/octocrab", branch = "list_files" }
anyhow = "1.0.62"
derive_builder = "0.11.2"
chrono = "0.4.22"
tokio = { version = "1.20.1", features = ["fs"] }
reqwest = "0.11.11"
flume = "0.10.14"
