[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
octocrab = { git = "https://github.com/tigercat2000/octocrab", branch = "list_files" }
anyhow = "1.0.57"
derive_builder = "0.11.2"
chrono = "0.4.19"
tokio = { version = "1.18.1", features = ["fs"] }
reqwest = "0.11.10"
flume = "0.10.12"
git2 = "0.15.0"
