[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
octocrab = "0.17.0"
anyhow = "1.0.65"
derive_builder = "0.11.2"
chrono = "0.4.22"
reqwest = "0.11.11"
flume = "0.10.14"
yaque = "0.6.4"
rmp-serde = "1.1.0"
async-fs = "1.6.0"
futures-lite = "1.12.0"
