[package]
name = "icondiffbot_test_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.17.0"
clap = { version = "3.2.22", features = ["derive"] }
tokio = { version = "1.21.1", features = ["full"] }
